### ISSUE TITLE
INCLUDES report as missing

### ISSUE THREAD

**Issue by TedThompson** [datajerk/c2t#10]
Maybe not an issue, but I had to change `#INCLUDE <fake6502.h>` to read `#INCLUDE "fake6502.h"` for the compiler to find it.  I had to do it for the `#INCLUDE <c2t.h>` as well.

This on on Windows 10 v1809 and MinGW v2013072200 (MinGW is not installed on my boot drive). 

Just an FYI.  After those edits, it compiled and ran beautifully.

**Comment by datajerk** [comment]
Fixed `README.md`.  All that was needed was `-I.` on the command line.  Thanks.
