### ISSUE TITLE
How to product 'gameserver' like .wav files from .dsk files?

### ISSUE THREAD

**Issue by zezba9000** [datajerk/c2t#12]
How to create a .wav without "INSTA-DISK" app?
Is there something missing in the docs for creating the self-launching tape .wav files as are in http://asciiexpress.net/gameserver/ ?

I'm trying to convert a .dsk to .wav without "INSTA-DISK" as I don't have a disk drive.

**Comment by datajerk** [comment]
Most disk-based apps were written specifically to use a disk (save state, load levels, etc...); it's in the code.  There are a few that can be extracted from the disk and run standalone (games, e.g. that do not require saving state, loading levels, etc..., i.e. no code to access disk directly); all of them the community could find are already on the gameserver.  Given that a disk is larger than RAM it's not possible to have all disk-based games load and play directly from RAM.  I'd recommend getting a floppy emulator that uses CF/SD cards for disk-based games.

As for single load binaries that you can extract from disk yourself (and that do not need the disk to operate), the c2t instructions do cover that case.  It is how all the wavs for the gameserver were created.

**Comment by zezba9000** [comment]
I'm asking for reasons related to HomeBrew (not official stuff).
I have a project CS2X I keep tools and future reference for: https://github.com/reignstudios/CS2X

If I get a chance to add Apple II support its nice knowing there is a tool out there that can convert .dsk to .wav
Loading games from tape is just cool.
