### ISSUE TITLE
Micro-Professor MPF-II Apple-II clone?

### ISSUE THREAD

**Issue by vitasam** [datajerk/c2t#14]
Hello,
what do you think is possible (in theory) to do the same for this Apple-II clone?
https://en.wikipedia.org/wiki/Microprofessor_II

I was not able to find any information about cassette data format of MPF-II, but comparing WAV files from Apple-II and MPF-II, it becomes clear that they are different.

Do you think it would be possible to reverse engineer an audio file from MPF-II if, for example, save a block of memory from Monitor with known bytes to a file?

**Comment by datajerk** [comment]
I'm sure it's possible, just takes time and physical access to HW.

**Comment by vitasam** [comment]
I have the HW, but have little knowledge about MPF-II modulation scheme. Do you have an idea where to start from?

**Comment by datajerk** [comment]
connect it to audacity (FOSS, but perhaps get an older version now since there's spyware in the latest version, you'll have to google for tips on getting a non-spyware version), write some data, look at the waveform

**Comment by vitasam** [comment]
Yep, I did it, it looks like there is 1 kHz of pilot signal, followed by probably frequency modulated signal (I see 2 periods of waves).
![image](https://user-images.githubusercontent.com/5597505/125210803-aa098380-e2aa-11eb-9664-d8ba415a1cda.png)

**Comment by datajerk** [comment]
Looks like zeros and ones to me.

**Comment by datajerk** [comment]
excellent news

**Comment by vitasam** [comment]
Thanks! 
By the way, do you know, is there a way to decode BASIC .wav file in to a text listing

**Comment by datajerk** [comment]
First you need to find a tool that will convert a basic binary dump to text listing.  I do not know of any.  Then you'll need to create a tool to read a wav and do the zero crossing detection so that you can extract the binary data for the 2nd tool; that should not be too hard, look at minimodem source as an example.

**Comment by vitasam** [comment]
Yep, I guess such converter (BASIC binary to text) is a main problem. So, basically it should be a complete BASIC interpreter on a PC, able to load and list the program text.

About .WAV file - I'm using 1-bit .BAW format with [ZXTapeRecorder2](https://trolsoft.ru/en/sch/zx-tapper) device, it works very reliably with MPF-II (after HW modification of MIC port). My guess is that 1-bit format should be relatively easy to convert into binary dump.
