### ISSUE TITLE
Web-based option w/emscripten

### ISSUE THREAD

**Issue by jepler** [datajerk/c2t#23]
Hi!

I thought it would be interesting to have a purely web-based version of c2t. I've made a prototype, and I'd love to discuss how/whether it would make sense to integrate with c2t, co-host and promote as a sibling project to Apple Disk/Game Server, etc.

[The prototype](https://www.unpythonic.net/web-c2t/) (source at https://github.com/jepler/web-c2t/) allows you to upload a disk image (dsk, do, po) and perform the conversion to audio locally within the web browser. No data is transmitted on the internet, and no server or back-end is necessary. This lacks a ton of polish, format/no-format and hifi/8k options, etc. I know enough about web technology to cobble, but not to make a polished final product.

Similar to the Apple ][ Disk Server, after conversion you just LOAD on the Apple II and then hit play on the generated audio file.

I've transferred a couple of disks this way, such as [Zork III](https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/games/adventure/infocom/zork_3/) and it seems to work just as well as the Disk Server or using c2t locally.

![image](https://user-images.githubusercontent.com/1517291/158024226-97d4a650-cd6a-4fdc-aece-24315c363ed5.png)

![PXL_20220312_151956529](https://user-images.githubusercontent.com/1517291/158023969-a04bbf22-2662-4826-8fbf-f8ad21efdb5e.jpg)

**Comment by datajerk** [comment]
You're the 2nd to do this.  Email me to discuss next steps.
