### ISSUE TITLE
Instadisk not working.

### ISSUE THREAD

**Issue by UniversalKing1999** [datajerk/c2t#26]
Hello.

After I make an audio file out of a disk image and try to load it in my apple 2e it gives me an error right after saying it started loading instadisk, eta 9 sec. I also can't load files from the apple disk server. What might cause this problem?

P.S. I read somewhere that it only supports NTSC computers and not PAL ones. (USA and Euro ones). I am using my computer in Europe but I ordered it from the USA, so I believe that it's not a Euro version.
Thanks in advance.

**Comment by datajerk** [comment]
The most common issues:

- Audio volume too low.
- .wav file was converted by player, e.g. to mp3.  When testing make sure you're streaming directly from website and not downloading to a player that may compress the audio.  With your local test what player are you using?
- Some browsers break the audio.  What OS/browser are you using?
- CPU not running at 1MHz.  c2t is very sensitive to CPU speed, hence "PAL ones" could possibly have issues, but I've not received any reports directly of PAL not working that I recall.
- Some players, e.g. a 10-year old Mac Pro I have will not play correctly the asymmetrical .wav files (diskserver hi-fi).  If testing locally try c2t vs c2t-96h.  On the diskserver try lo-fi (8000 bps vs hi-fi 9600 bps).  This is rarely a problem I've only found with old laptops.  What HW are you using?

**Comment by UniversalKing1999** [comment]
Hello.

Thank you for replying. I can get the games from apple game server just fine, using a regular aux cable. I am using a Lenovo Thinkpad T460, Chrome as my browser and windows 10. When I convert .dsk files with c2t (both c2t and c2t-96h) I get .wav files that I play with VLC media player. When I try to load something I crank up the volume to 100 on my computer. The only things that I can load from the Lenovo to my apple 2e are the gameserver games, but only lo-fi ones, hi-fi ones give me an error on the apple side. The disksserver and c2t files start up normally but then give an error, right after starting to load instadisk. Tomorrow I can post a picture or a small video too. Now, I don't know if the apple is running 1MHz or not, is there any way to test it?

Thanks in advance.

**Comment by datajerk** [comment]
I have a T460s with Linux I can test from to rule out HW incompatibility.  I'll try to test within the next week.  Can you try a phone or other computer?  As for measuring performance, does your //e have a clock card?  If so try: https://github.com/datajerk/c2t/blob/master/tests/apple2pi.wav.  Just "LOAD" then play with browser.  This does not use hi-fi.  It should take 1 min 54 sec for 1000 digits.  If you do not have clock card, then record screen video with phone, measure the time from when you hit enter (after 1000) until it reports done using something like VLC to scrub the video.

**Comment by UniversalKing1999** [comment]
Hello!

I tried using my phone, again I can only load lo-fi gameserver games and not diskserver ones. I tried using a high-quality aux cable but to no avail. I do not have a clock card. When I tried playing the apple2pi benchmark file (from my computer and my phone, browser and by players) I get an error too. (I'll post a picture.) Sorry for the low quality of the picture, my phone's camera has been broken like that for months. 
![IMG_20221212_095927](https://user-images.githubusercontent.com/92952136/207011315-e85d4c06-2633-49ba-a017-9c0be98f39aa.jpg)

**Comment by datajerk** [comment]
ETA should be 22 sec, that version may be hifi.  I just updated git repo, download and try again.

**Comment by datajerk** [comment]
With disks lo-fi is 8000 and hi-fi is 9600.  With gameserver lofi is 1333 hifi is 8000.  c2t can produce 1333 and 8000 bps wavs.  c2t-96h 1333/9600.  

At this point i'm stumped as to why the 8000/9600 wav files fail you.

**Comment by UniversalKing1999** [comment]
Well, I might have an earlier revision of the computer, or maybe a bad ram chip. But, how to convert .dsk files into 1333bps using c2t? Is there a special command?

**Comment by datajerk** [comment]
.dsk -> .wav at 1333 is not supported.  it'd take far too long increasing the probability of a line error.  c2t is fire and forget with error detection, but no error correction (re-transmit).  if you want to create disk images with audio cable, take a look at https://adtpro.com/.  ADT uses both cassette ports and re-transmit on error.  ADT can bootstrap over audio as well.

**Comment by UniversalKing1999** [comment]
Okay. Thank you for replying and helping.

Cheers!
