### ISSUE TITLE
not able to compile in ubuntu linux

### ISSUE THREAD

**Issue by fperdigon** [datajerk/c2t#31]
Hello, I am not able to compile on ubuntu 22.04
I am getting the following error.
Despite following https://github.com/datajerk/c2t/blob/master/ubuntu_notes.md
make: xcrun: No such file or directory

xcrun is a macOS related module I don't get why this is happening
Many thanks in advance

**Comment by fperdigon** [comment]
managed to get it to compile by modifying the Makefile. I will do a PR soon

**Comment by datajerk** [comment]
I fixed Makefile, try again.
