### ISSUE TITLE
Build errors on Linux

### ISSUE THREAD

**Issue by fabiopjve** [datajerk/c2t#32]
Hi, I am trying to build from source on Linux Mint but I am getting several errors.
First the tar command fails:
curl -sLO https://github.com/mrdudz/cc65-old/raw/master/cc65-sources-2.13.3.tar.bz2
tar zxf cc65-sources-2.13.3.tar.bz2

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make: *** [Makefile:52: cc65-2.13.3/bin/cl65] Error 2
-------------------------------------------------------------------------
I installed cc65 and removed the requirement of cc65-2.13.3/bin/cl65 from the Makefile.
Now I can have make to try to build the code but I get multiple compiler errors: all related to undeclared symbols:
c2t-96h.c:710:42: error: ‘inflatecode’ undeclared (first use in this function); did you mean ‘inflateEnd’?
  710 |                         for(j=0;j<sizeof(inflatecode)/sizeof(char);j++) {
      |                                          ^~~~~~~~~~~
      |                                          inflateEnd
Same for fastload8000, fastloadcd, diskload8000, diskload9600, diskloadcode2 and diskloadcode3.
What am I doing wrong? I don't see these arrays declared in the c2t.c source.

**Comment by datajerk** [comment]
Fixed and verified with Ubuntu 22.04.  Please try again.

**Comment by datajerk** [comment]
Just tested with mint 21.3 as well.

**Comment by fabiopjve** [comment]
Yes, the new commit fixed everything, thanks!
