### ISSUE TITLE
Can a ProDOS formatted Insta-disk be produced with c2t?

### ISSUE THREAD

**Issue by devorn** [datajerk/c2t#33]
I compiled version 0.997 and it is generally working amazingly well. This is a truly impressive concept and program.

However I am having difficulty determining if I can use this utility to package a ProDOS disk image of file type '.po' and how/if I would do that?

When using the 'c2t -8 prodos243.po prodos243.wav' for example, the wave file is produced in 28k segments.
The resultant .wav file is loaded on my old iPhone SE (with audio out jack). 
Applesoft LOAD command loads the file successfully, formats the blank disk in drive 1 and writes the data.

However the Apple II crashes to monitor when I try and boot the disk, presumably because the interleave and sector formats of a ProDOS disk are quite different than a DOS 3.3 that the program is designed to handle. 
Attempts to read the catalog of the produced disk from a known utility program is also unsuccessful.

Is there any particular or recommended mechanism of managing a .po image with c2t ?

**Comment by datajerk** [comment]
Have you tried `c2t-96h`?  That has support for prodos order.

**Comment by devorn** [comment]
Thanks for the hints and the code. 

I compiled c2t-96h (v0.997) and it worked like a charm with a .po (proDOS format image). 

Loaded up via my old iPhone SE (which is a convenient player of .wav files, since it has a 3.5mm audio outlet socket). 

Success!


![image](https://github.com/datajerk/c2t/assets/25177740/82aa5827-6dcb-49c6-8fda-37fab65abc91)

**Comment by datajerk** [comment]
Good news.  Newer iPhones with lighting or usb-c to 3.5mm also work.
